ruta get para profesionales creados
FedeMontanari/proyecto-final-29b-backend pull request #18
Opened 2022-10-26 21:57 UTC by IggyMartin

2022-10-26 22:44 UTC, FedeMontanari requested changes

2022-10-26 22:44 UTC, FedeMontanari commented on src/routes/Controllers/getProfessionals.js
> +const {Professional} = require('../../models/professional.js')
el import se hace de ('../../db')

2022-10-26 22:44 UTC, FedeMontanari commented on src/routes/Controllers/getProfessionals.js
> +        return res.send(allProfessionals)
aca seria res.json

2022-10-27 18:03 UTC, Erne5 approved these changes

2022-10-27 18:03 UTC, FedeMontanari approved these changes

2022-10-27 18:03 UTC, merged